### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by adrinjalali** [truly-irham/gdm-prime#1]
@truly-irham this fails to compile for me:

```py
ninja: Entering directory `/tmp/gdm-prime/src/build'
[3/298] Generating gdbus source daemon/gdm-dbus-glue.c
FAILED: daemon/gdm-dbus-glue.c 
/usr/bin/gdbus-codegen --c-generate-autocleanup all --interface-prefix org.freedesktop.DBus --c-namespace GdmDBus --body --output daemon/gdm-dbus-glue.c ../gdm/daemon/org.freedesktop.DBus.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[4/298] Generating gdbus header daemon/gdm-dbus-glue.h
FAILED: daemon/gdm-dbus-glue.h 
/usr/bin/gdbus-codegen --c-generate-autocleanup all --interface-prefix org.freedesktop.DBus --c-namespace GdmDBus --header --output daemon/gdm-dbus-glue.h ../gdm/daemon/org.freedesktop.DBus.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[5/298] Generating gdbus header daemon/gdm-display-glue.h
FAILED: daemon/gdm-display-glue.h 
/usr/bin/gdbus-codegen --c-generate-autocleanup all --interface-prefix org.gnome.DisplayManager --c-namespace GdmDBus --header --output daemon/gdm-display-glue.h ../gdm/daemon/gdm-display.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[6/298] Generating gdbus source daemon/gdm-display-glue.c
FAILED: daemon/gdm-display-glue.c 
/usr/bin/gdbus-codegen --c-generate-autocleanup all --interface-prefix org.gnome.DisplayManager --c-namespace GdmDBus --body --output daemon/gdm-display-glue.c ../gdm/daemon/gdm-display.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[16/298] Compiling C object common/libgdmcommon.a.p/gdm-common.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by truly-irham** [comment]
Hi, I have just tried compiling it and it compiles successfully. There's probably something wrong on your build dependencies. Also you might need to report this issue on the official repo instead. Cheers!
